from setuptools import setup, find_packages
from glob import glob

setup(
   name='miricoord',
   version='1.3.0',
   description='MIRI coordinate transforms',
   author='David R. Law',
   author_email='dlaw@stsci.edu',
   packages=find_packages(),
   data_files=[
       ('data/crds/cdp6',glob('data/crds/cdp6/*')),
       ('data/crds/cdp7',glob('data/crds/cdp7/*')),
       ('data/crds/cdp7b3',glob('data/crds/cdp7b3/*')),
       ('data/crds/cdp8',glob('data/crds/cdp8/*')),
       ('data/crds/flt1',glob('data/crds/flt1/*')),
       ('data/crds/flt2',glob('data/crds/flt2/*')),
       ('data/crds/flt3',glob('data/crds/flt3/*')),
       ('data/crds/flt4',glob('data/crds/flt4/*')),
       ('data/crds/flt5',glob('data/crds/flt5/*')),
       ('data/crds/flt6',glob('data/crds/flt6/*')),
       ('data/crds/flt7',glob('data/crds/flt7/*')),
       ('data/dithers',glob('data/dithers/*')),
       ('data/fits/cdp6',glob('data/fits/cdp6/*')),
       ('data/fits/cdp7',glob('data/fits/cdp7/*')),
       ('data/fits/cdp7beta3',glob('data/fits/cdp7beta3/*')),
       ('data/fits/cdp8b',glob('data/fits/cdp8b/*')),
       ('data/fits/flt1',glob('data/fits/flt1/*')),
       ('data/fits/flt2',glob('data/fits/flt2/*')),
       ('data/fits/flt3',glob('data/fits/flt3/*')),
       ('data/fits/flt4',glob('data/fits/flt4/*')),
       ('data/fits/flt5',glob('data/fits/flt5/*')),
       ('data/fits/flt6',glob('data/fits/flt6/*')),
       ('data/fits/flt7',glob('data/fits/flt7/*')),
   ],
   include_package_data=True,
   install_requires=['jwst', 'pysiaf', 'jupyter', 'matplotlib'],
)
